// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaRegistro.Datos;

#nullable disable

namespace VeterinariaRegistro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VeterinariaRegistro.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRazaMascota")
                        .HasColumnType("int");

                    b.Property<string>("ImagenMascota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMascota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePropietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdRazaMascota");

                    b.ToTable("Mascota");
                });

            modelBuilder.Entity("VeterinariaRegistro.Models.RazaMascota", b =>
                {
                    b.Property<int>("IdRaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRaza"), 1L, 1);

                    b.Property<int>("IdTipoMascota")
                        .HasColumnType("int");

                    b.Property<string>("NombreRaza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRaza");

                    b.HasIndex("IdTipoMascota");

                    b.ToTable("RazaMascota");

                    b.HasData(
                        new
                        {
                            IdRaza = 1,
                            IdTipoMascota = 1,
                            NombreRaza = "Labrador"
                        },
                        new
                        {
                            IdRaza = 2,
                            IdTipoMascota = 1,
                            NombreRaza = "Bulldog"
                        },
                        new
                        {
                            IdRaza = 3,
                            IdTipoMascota = 2,
                            NombreRaza = "Siamés"
                        },
                        new
                        {
                            IdRaza = 4,
                            IdTipoMascota = 2,
                            NombreRaza = "Persa"
                        },
                        new
                        {
                            IdRaza = 5,
                            IdTipoMascota = 3,
                            NombreRaza = "Canario"
                        },
                        new
                        {
                            IdRaza = 6,
                            IdTipoMascota = 3,
                            NombreRaza = "Periquito"
                        });
                });

            modelBuilder.Entity("VeterinariaRegistro.Models.TipoMascota", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"), 1L, 1);

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipo");

                    b.ToTable("TipoMascota");

                    b.HasData(
                        new
                        {
                            IdTipo = 1,
                            NombreTipo = "Perro"
                        },
                        new
                        {
                            IdTipo = 2,
                            NombreTipo = "Gato"
                        },
                        new
                        {
                            IdTipo = 3,
                            NombreTipo = "Pájaro"
                        });
                });

            modelBuilder.Entity("VeterinariaRegistro.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VeterinariaRegistro.Models.Mascota", b =>
                {
                    b.HasOne("VeterinariaRegistro.Models.RazaMascota", "RazaMascota")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdRazaMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RazaMascota");
                });

            modelBuilder.Entity("VeterinariaRegistro.Models.RazaMascota", b =>
                {
                    b.HasOne("VeterinariaRegistro.Models.TipoMascota", "TipoMascota")
                        .WithMany("RazasMascotas")
                        .HasForeignKey("IdTipoMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMascota");
                });

            modelBuilder.Entity("VeterinariaRegistro.Models.RazaMascota", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("VeterinariaRegistro.Models.TipoMascota", b =>
                {
                    b.Navigation("RazasMascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
